[project]
name = "call-me-maybe"
version = "1.0.0"
description = "Constrained-decoding function calling with a small LLM."
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pydantic>=2",
    "llm-sdk",
]

[tool.uv.sources]
llm-sdk = { path = "llm_sdk", editable = true }

[tool.mypy]
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.flake8]
max-line-length = 79
