[project]
name = "call-me-maybe"
version = "1.0.0"
description = "Function calling in LLMs via constrained decoding"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.24",
    "pydantic>=2.0",
    "llm-sdk",
]

[tool.uv.sources]
llm-sdk = { path = "llm_sdk" }

[tool.flake8]
max-line-length = 100

[tool.mypy]
exclude = ['^llm_sdk/']

[[tool.mypy.overrides]]
module = ["llm_sdk", "llm_sdk.*"]
ignore_missing_imports = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
